In [2]:
import sys
from pathlib import Path

import pandas as pd

sys.path.append(str(Path.cwd().parent))

from src.splitter import splitter

d:\ML\Elden_RAG\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
all_chunks = splitter.process_folder(Path('../data'))

Обработан файл ..\data\Адан, вор огня.md, создано 18 чанков
Обработан файл ..\data\Адула, дракон блестящих камней.md, создано 26 чанков
Обработан файл ..\data\Алекто, главарь Чёрных ножей.md, создано 31 чанков
Обработан файл ..\data\Алый волк Радагона.md, создано 20 чанков
Обработан файл ..\data\Алый волк чемпиона.md, создано 17 чанков
Обработан файл ..\data\Апостол божественной кожи.md, создано 23 чанков
Обработан файл ..\data\Аристократ божественной кожи.md, создано 26 чанков
Обработан файл ..\data\Астель, Звёзды Тьмы.md, создано 34 чанков
Обработан файл ..\data\Астель, Рождённый Бездной.md, создано 49 чанков
Обработан файл ..\data\Бастард Леонин.md, создано 20 чанков
Обработан файл ..\data\Бейл Ужасный.md, создано 58 чанков
Обработан файл ..\data\Болс, карианский рыцарь.md, создано 14 чанков
Обработан файл ..\data\Борелис Леденящий Туман.md, создано 33 чанков
Обработан файл ..\data\Будущий консорт Радан.md, создано 91 чанков
Обработан файл ..\data\Великий змей Теодорикс.md, создано 27 чанков
Обработан файл ..\data\Великий красный медведь Ральва.md, создано 22 чанков
Обработан файл ..\data\Великий красный медведь Ругали.md, создано 23 чанков
Обработан файл ..\data\Взрослый зверь Падающей звезды.md, создано 39 чанков
Обработан файл ..\data\Вик, рыцарь Круглого стола.md, создано 26 чанков
Обработан файл ..\data\Владыка драконов Пласидусакс.md, создано 83 чанков
Обработан файл ..\data\Вождь кровопускателей.md, создано 18 чанков
Обработан файл ..\data\Воин-бастард.md, создано 18 чанков
Обработан файл ..\data\Воплощение Древа Упадка.md, создано 22 чанков
Обработан файл ..\data\Воплощение Древа Эрд.md, создано 29 чанков
Обработан файл ..\data\Герои Фии.md, создано 8 чанков
Обработан файл ..\data\Гидеон Офнир.md, создано 91 чанков
Обработан файл ..\data\Гнилостное воплощение.md, создано 30 чанков
Обработан файл ..\data\Гнилостный древесный дух.md, создано 27 чанков
Обработан файл ..\data\Гнилостный дуэлянт, хранитель могил.md, создано 21 чанков
Обработан файл ..\data\Гниющий Экзикес.md, создано 28 чанков
Обработан файл ..\data\Годрик Сторукий.md, создано 51 чанков
Обработан файл ..\data\Годфри, первый повелитель Элдена (Золотая тень).md, создано 18 чанков
Обработан файл ..\data\Годфри, первый повелитель Элдена.md, создано 72 чанков
Обработан файл ..\data\Годфрой Сторукий.md, создано 14 чанков
Обработан файл ..\data\Граф Имир, матерь Пальцев.md, создано 8 чанков
Обработан файл ..\data\Греил, крылатый дракон.md, создано 24 чанков
Обработан файл ..\data\Грейолл, Великая драконица.md, создано 16 чанков
Обработан файл ..\data\Гуго, боевой маг.md, создано 7 чанков
Обработан файл ..\data\Двое из божественной кожи.md, создано 22 чанков
Обработан файл ..\data\Дева-похитительница.md, создано 37 чанков
Обработан файл ..\data\Дейн Сухой Лист.md, создано 15 чанков
Обработан файл ..\data\Дракон зубатой горы.md, создано 24 чанков
Обработан файл ..\data\Дракон смерти.md, создано 30 чанков
Обработан файл ..\data\Дракон-лич Фортисакс.md, создано 31 чанков
Обработан файл ..\data\Драконий солдат Нокстеллы.md, создано 28 чанков
Обработан файл ..\data\Драконий солдат.md, создано 22 чанков
Обработан файл ..\data\Драконий Страж Древа.md, создано 33 чанков
Обработан файл ..\data\Древний герой Замора.md, создано 26 чанков
Обработан файл ..\data\Древний дракон Лансеакс.md, создано 24 чанков
Обработан файл ..\data\Древний дракон Сенессакс.md, создано 25 чанков
Обработан файл ..\data\Древний человек-дракон.md, создано 6 чанков
Обработан файл ..\data\Дух величавого предка.md, создано 38 чанков
Обработан файл ..\data\Дух предка.md, создано 17 чанков
Обработан файл ..\data\Дуэлянт, хранитель могил.md, создано 19 чанков
Обработан файл ..\data\Жрец крови Эсгар.md, создано 7 чанков
Обработан файл ..\data\Зверочеловек из Фарум-Азулы.md, создано 23 чанков
Обработан файл ..\data\Зверь Падающей звезды.md, создано 25 чанков
Обработан файл ..\data\Зверь Элдена.md, создано 60 чанков
Обработан файл ..\data\Золотой гиппопотам.md, создано 22 чанков
Обработан файл ..\data\Изъязвлённый древесный дух.md, создано 37 чанков
Обработан файл ..\data\Командир Найлл.md, создано 35 чанков
Обработан файл ..\data\Командир О'Нил.md, создано 23 чанков
Обработан файл ..\data\Королева полулюдей Гилика.md, создано 9 чанков
Обработан файл ..\data\Королева полулюдей Марго.md, создано 6 чанков
Обработан файл ..\data\Королева полулюдей Мэгги.md, создано 7 чанков
Обработан файл ..\data\Королева Реннала Полнолунная.md, создано 84 чанков
Обработан файл ..\data\Королевский призрак.md, создано 30 чанков
Обработан файл ..\data\Крестоносец-бастард.md, создано 15 чанков
Обработан файл ..\data\Кристалиец.md, создано 37 чанков
Обработан файл ..\data\Кровавый аристократ.md, создано 16 чанков
Обработан файл ..\data\Лабирит, проклятый клинок.md, создано 19 чанков
Обработан файл ..\data\Лодочник Тибия.md, создано 22 чанков
Обработан файл ..\data\Ложная Слеза.md, создано 10 чанков
Обработан файл ..\data\Лоретта, королевский рыцарь.md, создано 18 чанков
Обработан файл ..\data\Лоретта, рыцарь Святого Древа.md, создано 24 чанков
Обработан файл ..\data\Магмовый змей Макар.md, создано 28 чанков
Обработан файл ..\data\Магмовый змей.md, создано 28 чанков
Обработан файл ..\data\Маления, Клинок Микеллы.md, создано 111 чанков
Обработан файл ..\data\Маликет Чёрный Клинок.md, создано 94 чанков
Обработан файл ..\data\Маргит, Ужасное Знамение.md, создано 45 чанков
Обработан файл ..\data\Медведь рун.md, создано 31 чанков
Обработан файл ..\data\Мессмер Колосажатель.md, создано 58 чанков
Обработан файл ..\data\Мечница-нокс.md, создано 16 чанков
Обработан файл ..\data\Миранда Смертоцвет.md, создано 29 чанков
Обработан файл ..\data\Мог Повелитель Крови.md, создано 72 чанков
Обработан файл ..\data\Мог, Знамение.md, создано 28 чанков
Обработан файл ..\data\Монах-нокс.md, создано 14 чанков
Обработан файл ..\data\Морготт, король знамений.md, создано 61 чанков
Обработан файл ..\data\Некромант Гаррис.md, создано 11 чанков
Обработан файл ..\data\Ночной всадник.md, создано 37 чанков
Обработан файл ..\data\Огненный великан.md, создано 40 чанков
Обработан файл ..\data\Ониксовый повелитель.md, создано 16 чанков
Обработан файл ..\data\Отважные горгульи.md, создано 15 чанков
Обработан файл ..\data\Охотник за колокольными сферами.md, создано 33 чанков
Обработан файл ..\data\Парфюмерша Триша.md, создано 9 чанков
Обработан файл ..\data\Погребальная птица.md, создано 29 чанков
Обработан файл ..\data\Предводитель полулюдей.md, создано 21 чанков
Обработан файл ..\data\Приращенный отпрыск.md, создано 26 чанков
Обработан файл ..\data\Птица смерти.md, создано 19 чанков
Обработан файл ..\data\Радагон из Золотого порядка.md, создано 78 чанков
Обработан файл ..\data\Радан Бич Звёзд.md, создано 96 чанков
Обработан файл ..\data\Рикард, богохульный владыка.md, создано 67 чанков
Обработан файл ..\data\Родич гнили.md, создано 13 чанков
Обработан файл ..\data\Родич Чёрного Клинка.md, создано 40 чанков
Обработан файл ..\data\Рыцарь Горнила Ордовис.md, создано 34 чанков
Обработан файл ..\data\Рыцарь Горнила Силурия.md, создано 16 чанков
Обработан файл ..\data\Рыцарь Горнила.md, создано 38 чанков
Обработан файл ..\data\Рыцарь Силурии.md, создано 20 чанков
Обработан файл ..\data\Рыцарь Смерти.md, создано 22 чанков
Обработан файл ..\data\Рыцарь чистой гнили.md, создано 27 чанков
Обработан файл ..\data\Рыцарь-ищейка Дарривил.md, создано 13 чанков
Обработан файл ..\data\Рыцарь-ищейка.md, создано 19 чанков
Обработан файл ..\data\Священный танцующий лев.md, создано 47 чанков
Обработан файл ..\data\Смараг, дракон блестящих камней.md, создано 25 чанков
Обработан файл ..\data\Солдат Годрика.md, создано 16 чанков
Обработан файл ..\data\Страж Древа.md, создано 31 чанков
Обработан файл ..\data\Страж-голем.md, создано 42 чанков
Обработан файл ..\data\Тень кладбища.md, создано 17 чанков
Обработан файл ..\data\Тролль-камнекоп.md, создано 26 чанков
Обработан файл ..\data\Тыквоголовый безумец.md, создано 26 чанков
Обработан файл ..\data\Убийца знамений.md, создано 20 чанков
Обработан файл ..\data\Убийца из Чёрных ножей.md, создано 30 чанков
Обработан файл ..\data\Ужасные близнецы.md, создано 10 чанков
Обработан файл ..\data\Улитка-призывательница духов.md, создано 12 чанков
Обработан файл ..\data\Цербер кладбища Древа Эрд.md, создано 26 чанков
Обработан файл ..\data\Червемордый.md, создано 27 чанков
Обработан файл ..\data\Чешуйчатый бастард.md, создано 12 чанков
Обработан файл ..\data\Эгхил, крылатый дракон.md, создано 28 чанков
Обработан файл ..\data\Элемер из Шипов.md, создано 29 чанков
Обработан файл ..\data\Яростный дуэлянт.md, создано 17 чанков

In [4]:

records = []
for doc in all_chunks:
    records.append({
        'text': doc.page_content,
        'length': len(doc.page_content),
        'name': doc.metadata.get('name'),
        'chapter': doc.metadata.get('chapter'),
        'section': doc.metadata.get('section'),
        'subsection': doc.metadata.get('subsection')
    })

chunks_df = pd.DataFrame(records)
chunks_df = chunks_df[['text', 'length', 'name', 'chapter', 'section', 'subsection']]

chunks_df.head()

,text,length,name,chapter,section,subsection
0,"Предметы; Адан, вор огня\nПламя падшего бога",43,"Адан, вор огня",Предметы,NaN,NaN
1,"Краткая информация; Адан, вор огня\nАдан, вор ...",116,"Адан, вор огня",Краткая информация,NaN,NaN
2,"Описание; Адан, вор огня\nОднажды Адан украл л...",322,"Адан, вор огня",Описание,NaN,NaN
3,"Местонахождение; Адан, вор огня\nОзёрная Лиурн...",73,"Адан, вор огня",Местонахождение,NaN,NaN
4,"Защита; Адан, вор огня\nБаланс=100, Яд=232, Кр...",128,"Адан, вор огня",Защита,NaN,NaN

In [5]:
chunks_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3903 entries, 0 to 3902
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   text        3903 non-null   str
 1   length      3903 non-null   int64
 2   name        3903 non-null   str
 3   chapter     3901 non-null   str
 4   section     1716 non-null   str
 5   subsection  312 non-null    str
dtypes: int64(1), str(5)
memory usage: 183.1 KB

In [6]:
chunks_df['length'].describe()

count    3903.000000
mean      273.692544
std       104.158251
min        29.000000
25%       192.000000
50%       287.000000
75%       372.000000
max       495.000000
Name: length, dtype: float64

In [7]:
def get_header_length(row):
    parts = [str(row['name']), str(row['chapter']), str(row['section']), str(row['subsection'])]
    parts = [p for p in parts if p != 'nan']
    return len("; ".join(parts) + "\n")

chunks_df['headers_length'] = chunks_df.apply(get_header_length, axis=1)

In [8]:
chunks_df['headers_length'].describe()

count    3903.000000
mean       41.906226
std        16.275039
min        13.000000
25%        31.000000
50%        39.000000
75%        49.000000
max       138.000000
Name: headers_length, dtype: float64

In [9]:
chunks_df[chunks_df['headers_length'] > 100]

,text,length,name,chapter,section,subsection,headers_length
664,Тактика; Тактика №2: Метеорит Астеля; Тактика ...,135,Владыка драконов Пласидусакс,Тактика,Тактика №2: Метеорит Астеля,Тактика №2.1: Метеорит Астеля без праха,108
665,Тактика; Тактика №2: Метеорит Астеля; Тактика ...,466,Владыка драконов Пласидусакс,Тактика,Тактика №2: Метеорит Астеля,Тактика №2.1: Метеорит Астеля без праха,108
666,Тактика; Тактика №2: Метеорит Астеля; Тактика ...,300,Владыка драконов Пласидусакс,Тактика,Тактика №2: Метеорит Астеля,Тактика №2.1: Метеорит Астеля без праха,108
667,Тактика; Тактика №2: Метеорит Астеля; Тактика ...,464,Владыка драконов Пласидусакс,Тактика,Тактика №2: Метеорит Астеля,Тактика №2.1: Метеорит Астеля без праха,108
668,Тактика; Тактика №2: Метеорит Астеля; Тактика ...,164,Владыка драконов Пласидусакс,Тактика,Тактика №2: Метеорит Астеля,Тактика №2.1: Метеорит Астеля без праха,108
803,Тактика; Крепость Круглого стола (главный зал)...,140,Гидеон Офнир,Тактика,Крепость Круглого стола (главный зал),Заговорить после отдыха у места благодати,104
805,Тактика; Крепость Круглого стола (главный зал)...,280,Гидеон Офнир,Тактика,Крепость Круглого стола (главный зал),Выбрать вариант «Почему я здесь на правах гостя?»,112
806,Тактика; Крепость Круглого стола (главный зал)...,324,Гидеон Офнир,Тактика,Крепость Круглого стола (главный зал),Выбрать вариант «Почему я здесь на правах гостя?»,112
813,Тактика; Крепость Круглого стола (кабинет); За...,451,Гидеон Офнир,Тактика,Крепость Круглого стола (кабинет),Заговорить после получения второй великой руны,105
815,Тактика; Крепость Круглого стола (кабинет); Вы...,365,Гидеон Офнир,Тактика,Крепость Круглого стола (кабинет),Выбрать опцию «Куда мне идти?» (после убийства...,115
1891,Диалоги; После боя; После согласия на перерожд...,152,Королева Реннала Полнолунная,Диалоги,После боя,После согласия на перерождение (перед распреде...,118
2266,Диалоги; Неиспользованные строки; Переход во в...,223,"Маления, Клинок Микеллы",Диалоги,Неиспользованные строки,Переход во вторую стадию (говорит Микелла),102
2356,Диалоги; Если игрок не завершил квест Гурранка...,140,Маликет Чёрный Клинок,Диалоги,Если игрок не завершил квест Гурранка,Если убил игрока в первой фазе,102
2358,Диалоги; Если игрок не завершил квест Гурранка...,143,Маликет Чёрный Клинок,Диалоги,Если игрок не завершил квест Гурранка,Если убил игрока во второй фазе,103
2592,Тактика; Тактика через оружие с эффектом чёрно...,361,Мог Повелитель Крови,Тактика,Тактика через оружие с эффектом чёрного пламен...,NaN,138
2593,Тактика; Тактика через оружие с эффектом чёрно...,451,Мог Повелитель Крови,Тактика,Тактика через оружие с эффектом чёрного пламен...,NaN,138
2594,Тактика; Тактика через оружие с эффектом чёрно...,453,Мог Повелитель Крови,Тактика,Тактика через оружие с эффектом чёрного пламен...,NaN,138
2595,Тактика; Тактика через оружие с эффектом чёрно...,266,Мог Повелитель Крови,Тактика,Тактика через оружие с эффектом чёрного пламен...,NaN,138
2596,Тактика; Тактика через оружие с эффектом чёрно...,435,Мог Повелитель Крови,Тактика,Тактика через оружие с эффектом чёрного пламен...,NaN,138
2597,Тактика; Тактика через оружие с эффектом чёрно...,396,Мог Повелитель Крови,Тактика,Тактика через оружие с эффектом чёрного пламен...,NaN,138
2598,Тактика; Тактика через оружие с эффектом чёрно...,260,Мог Повелитель Крови,Тактика,Тактика через оружие с эффектом чёрного пламен...,NaN,138
2599,Тактика; Тактика через оружие с эффектом чёрно...,403,Мог Повелитель Крови,Тактика,Тактика через оружие с эффектом чёрного пламен...,NaN,138
2600,Тактика; Тактика через оружие с эффектом чёрно...,495,Мог Повелитель Крови,Тактика,Тактика через оружие с эффектом чёрного пламен...,NaN,138
2601,Тактика; Тактика через оружие с эффектом чёрно...,183,Мог Повелитель Крови,Тактика,Тактика через оружие с эффектом чёрного пламен...,NaN,138
2602,Тактика; Тактика через оружие с эффектом чёрно...,440,Мог Повелитель Крови,Тактика,Тактика через оружие с эффектом чёрного пламен...,NaN,138
2603,Тактика; Тактика через оружие с эффектом чёрно...,385,Мог Повелитель Крови,Тактика,Тактика через оружие с эффектом чёрного пламен...,NaN,138
3486,Атаки; Вторая фаза; Смертельный режим (только ...,365,Священный танцующий лев,Атаки,Вторая фаза,Смертельный режим (только босс у Руин древней ...,106